# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170401_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='aid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
