# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20170407_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.CharField(max_length=32),
        ),
    ]
