# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='telphone',
            field=models.IntegerField(default=None),
        ),
    ]
