# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20170411_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
